# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(507, 558)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 291, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 110, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 110, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 101, 21))
        self.label_2.setObjectName("label_2")
        self.listWidget_invalidas = QtWidgets.QListWidget(Dialog)
        self.listWidget_invalidas.setGeometry(QtCore.QRect(280, 200, 181, 311))
        self.listWidget_invalidas.setObjectName("listWidget_invalidas")
        self.listWidget_validas = QtWidgets.QListWidget(Dialog)
        self.listWidget_validas.setGeometry(QtCore.QRect(40, 200, 181, 311))
        self.listWidget_validas.setObjectName("listWidget_validas")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(290, 170, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(260, 60, 221, 21))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.lineEdit.cut) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Automata de validacion de placas</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Verificar"))
        self.label_2.setText(_translate("Dialog", "Ingresar  placa: "))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#00aa00;\">Placas Validas</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Placas Invalidas</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">KL-0001-A | MS-9999-Z</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.setWindowTitle("Validacion de Placas 203714")
    Dialog.show()
    sys.exit(app.exec_())
